version: 2.1
jobs:
  install_deps:
    docker:
      - image: giorgio14/elm-antd-ci:2.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "./showcase/package-lock.json" }}
            - dependency-cache-
      - run:
          name: "Install Showcase Dependencies"
          command: |
            echo "Node version: $(node -v)"
            echo "npm version: $(npm -v)"
            cd ./showcase
            npm install
      - save_cache:
          key: dependency-cache-{{ checksum "./showcase/package-lock.json" }}
          paths:
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - project/showcase/node_modules
            - .cache/Cypress 

  check_formatting:
    docker:
      - image: giorgio14/elm-antd-ci:2.5.0
    steps:
      - checkout
      - run:
          name: "Check formatting"
          command: |
            echo "> Checking formatting of package"
            elm-format --validate src
            echo "> Checking formatting of showcase"
            elm-format --validate showcase/src/elm

  verify_build:
    docker:
      - image: giorgio14/elm-antd-ci:2.5.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "Build package and showcase"
          command: |
            elm make
            cd showcase
            npm run build

  unit_tests:
    docker:
      - image: giorgio14/elm-antd-ci:2.5.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "Run unit tests"
          command: |
            ./scripts/run-unit-tests.sh

  visual_tests:
    docker:
      - image: giorgio14/elm-antd-ci:2.5.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/ 
      - run:
          name: "Run visual regression tests"
          command: |
            # WIP:
            # I want to only run visual tests when:
            # - code inside of src/Ant has changed
            # - code inside of showcase/src/elm/VisualTests.elm has changed
            # - code inside of showcase/visual-tests has changed
            # git diff --name-only master..$CIRCLE_BRANCH
            cd showcase
            npm run visual-tests:start-server &>/dev/null &
            # wait for visual testing app to compile
            sleep 7
            npm run visual-tests:run-tests
            
workflows:
  version: 2
  main:
    jobs:
      - install_deps
      - check_formatting
      - verify_build:
          requires:
            - install_deps
      - unit_tests:
          requires:
            - install_deps
      - visual_tests:
          requires:
            - install_deps
          filters:
            branches:
              ignore: master
